apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flink-jobmanager
  namespace: flink
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
      annotations:
        prometheus.io/port: "9249"
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: jobmanager
        image: protess/flink-demo:0.1.1
        args:
        - jobmanager
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob
        - containerPort: 6125
          name: query
        - containerPort: 8081
          name: ui
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: flink-jobmanager

